### ISSUE TITLE
No such file or directory: '/home/admin/ssd_data/core50/paths.pkl

### ISSUE THREAD

**Issue by ataftaf** [vlomonaco/ar1-pytorch#4]
Hello,

Thanks for the code. When I tried to run it, I got this error:

"Traceback (most recent call last):
  File "ar1star_lat_replay.py", line 87, in <module>
    dataset = CORE50(root='/home/admin/ssd_data/core50', scenario="nicv2_391")
  File "/content/ar1-pytorch/data_loader.py", line 94, in __init__
    with open(os.path.join(root, 'paths.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/ssd_data/core50/paths.pkl'

Thanks for helping me solve this issue

**Comment by vlomonaco** [comment]
Hi @ataftaf thanks for reporting the issue!

You need to download the CORe50 data manually e and change the "root" parameter accordingly!
You can download the data here: https://vlomonaco.github.io/core50/index.html#download

You need to download "paths.pkl", "labels.pkl" and "LUP.pkl" other than the actual images "cropped_128x128_images.zip" and put everything under the same root dir!

**Comment by ataftaf** [comment]
Appreciate your quick answer. I will try these and come back to you.
